theme: jekyll-theme-dinky
show_downloads: false
title: ITRavels
description: ðŸ‘€
is_project_page: false
repository_url:
show_repository_url: false
is_user_page: false
show_footer: false
plugins:
  - jemoji
